# Generated by Django 2.2.4 on 2020-04-07 12:08

from decimal import Decimal
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_rehive_extras.fields
import enumfields.fields
import service_stripe.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('stripe_api_key', models.CharField(max_length=100, null=True)),
                ('stripe_secret', models.CharField(max_length=150, null=True)),
                ('stripe_publishable_api_key', models.CharField(max_length=100, null=True)),
                ('stripe_success_url', models.CharField(max_length=150, null=True)),
                ('stripe_cancel_url', models.CharField(max_length=150, null=True)),
                ('stripe_return_url', models.CharField(max_length=150, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('display_code', models.CharField(blank=True, max_length=12, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('divisibility', models.IntegerField(default=2)),
                ('enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_stripe.Company')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identifier', models.UUIDField(db_index=True, unique=True)),
                ('token', models.CharField(max_length=200, null=True)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=64, null=True, unique=True)),
                ('stripe_payment_method_id', models.CharField(max_length=64, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_stripe.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identifier', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mode', enumfields.fields.EnumField(db_index=True, enum=service_stripe.enums.SessionMode, max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('session_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_stripe.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identifier', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', django_rehive_extras.fields.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=30)),
                ('status', enumfields.fields.EnumField(db_index=True, default='processing', enum=service_stripe.enums.PaymentStatus, max_length=24)),
                ('error', models.CharField(max_length=250, null=True)),
                ('collection', models.CharField(max_length=64, null=True)),
                ('txns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=list, size=None)),
                ('intent_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('next_action', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_stripe.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_stripe.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_company', to='service_stripe.User'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_currencies',
            field=models.ManyToManyField(related_name='_company_stripe_currencies_+', to='service_stripe.Currency'),
        ),
    ]
