# Generated by Django 2.2.4 on 2020-04-01 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_stripe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('display_code', models.CharField(blank=True, max_length=12, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('divisibility', models.IntegerField(default=2)),
                ('enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_stripe.Company')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
    ]
