# Generated by Django 2.2.4 on 2020-04-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_stripe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_payment_method_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='faked', max_length=64),
            preserve_default=False,
        ),
    ]
