# Generated by Django 2.2.4 on 2020-04-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_stripe', '0002_auto_20200409_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='stripe_cancel_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stripe_return_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stripe_success_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='return_url',
            field=models.URLField(default='https://faked.url/', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='cancel_url',
            field=models.URLField(default='https://faked.url/', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='success_url',
            field=models.URLField(default='https://faked.url/', max_length=250),
            preserve_default=False,
        ),
    ]
