# Generated by Django 2.2.2 on 2020-06-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_stripe', '0003_auto_20200417_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stripe_api_key',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stripe_publishable_api_key',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stripe_secret',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
