# Generated by Django 2.2.4 on 2021-02-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_stripe', '0004_auto_20200617_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='identifier',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='identifier',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
