deployment:
  command: [gunicorn, config.wsgi:application, --config, file:config/gunicorn.py]
  args:
  replicaCount: 3
  resources:
    requests:
      cpu: 50m
      memory: 350Mi
    limits:
      cpu: 500m
      memory: 1750Mi
image:
  pullPolicy: IfNotPresent
  repository: gcr.io/rehive-services/service-stripe
  tag: latest
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  enabled: true
  hosts:
    - stripe.services.rehive.io
  tls:
    - hosts:
        - stripe.services.rehive.io
      secretName: service-stripe-tls
postgres:
  enabled: true
  host: 172.26.144.2
  port: 5432
  db: service_stripe
  secret:
    key: postgres-password
    name: postgres
  user: service_stripe
service:
  externalPort: 80
  internalPort: 8000
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  name: nginx
  readinessProbe:
    httpGet:
      path: /readiness
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  type: NodePort
rabbitmq:
  enabled: false
redis:
  enabled: false
workers:
  enabled: false
