image:
  repository: rehive/spilo-11
  tag: 1.6.1
  pullPolicy: IfNotPresent
  init:
    command:
      - '/bin/sh'
    args:
      - '/launch.sh'
      - init
replicas: 1
debug: true
podAntiAffinity: soft
nodeSelector: {}
tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Equal
  value: postgres
resources: {}
bootstrapParameters:
  dcs:
    loop_wait: 30
    retry_timeout: 10
    ttl: 70
walE:
  enabled: true
  envDir: /home/postgres/etc/wal-e.d/env
  gcloudCredentials: gcloud-wale.json
  scheduleCronJob: 00 01 * * *
  retainBackups: 2
  s3Bucket:
  gcsBucket: service-stripe-staging-pgbackup
  backupThresholdMegabytes: 1024
  backupThresholdPercentage: 30
gcloudCredentials:
  enabled: true
  secretName: gcloud-wale
cloneWithWale:
  enabled: true
  cloneScope: patroni-service-stripe-patroni
  cloneWalGcsBucket: service-stripe-staging-pgbackup
  gcloudCredentials: gcloud-wale.json
  cloneWaleEnvDir: /home/postgres/etc/clone-wal-e.d/env
persistentVolume:
  accessModes:
  - ReadWriteOnce
  annotations:
    app: spilo
    release: patroni-service-stripe
  enabled: true
  size: 50Gi
  storageClass: patroni-standard
cleanup:
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/coreos/hyperkube
    tag: v1.8.4_coreos.0
rbac:
  create: true
serviceAccount:
  create: true
postgresParameters:
  bin_dir: /usr/lib/postgresql/9.6/bin
useConfigMaps: false
