deployment:
  command: ['gunicorn', 'config.wsgi:application', '--config', 'file:config/gunicorn.py']
  args: null
  replicaCount: 1
  resources:
    requests:
    limits:
image:
  pullPolicy: IfNotPresent
  repository: rehiveservices.azurecr.io/service-stripe
  tag: latest
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  enabled: true
  hosts:
  - stripe.s.services.rehive.io
  tls:
  - hosts:
    - stripe.s.services.rehive.io
    secretName: service-stripe-staging-tls
postgres:
  enabled: true
  host: patroni-service-stripe-patroni.service-stripe-staging.svc.cluster.local
  port: "5432"
  secret:
    key: password-admin
    name: patroni-service-stripe-patroni
  user: webapp
service:
  externalPort: 80
  internalPort: 8000
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  name: nginx
  readinessProbe:
    httpGet:
      path: /readiness
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  type: NodePort
imagePullSecrets:
  name: acr-secret
management:
  enabled: false
rabbitmq:
  enabled: false
redis:
  enabled: false
vendor:
  name: azure
workers:
  enabled: false
